# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_auto_20170902_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transactions.GameTransaction')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('won', models.BooleanField()),
                ('outcome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game', models.CharField(choices=[('BAML', 'BAML')], max_length=50)),
                ('choices', models.CharField(max_length=255)),
                ('roll', models.SmallIntegerField()),
            ],
        ),
    ]
